"""FastAPI application entry point scaffold."""

from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI
from fastapi import HTTPException
from fastapi.responses import FileResponse
from fastapi.responses import HTMLResponse

from trafficcam.api.routes import router
from trafficcam.web.map_page import render_map_page

app = FastAPI(title="Traffic Cam API")
app.include_router(router, prefix="/api")


def _resolve_output_asset(asset_path: str) -> Path:
    output_root = (Path.cwd() / "output").resolve()
    candidate = (output_root / asset_path).resolve()
    try:
        candidate.relative_to(output_root)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail="Unknown output asset") from exc
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail="Unknown output asset")
    return candidate


@app.get("/", response_class=HTMLResponse)
def dashboard() -> HTMLResponse:
    """Render the interactive congestion map."""
    return HTMLResponse(render_map_page())


@app.get("/output/{asset_path:path}")
def output_asset(asset_path: str) -> FileResponse:
    """Serve captured frames and debug overlays generated by the pipeline."""
    return FileResponse(_resolve_output_asset(asset_path))


@app.get("/health")
def health() -> dict:
    """Return a simple health response."""
    return {"status": "ok"}
