"""FastAPI application entry point scaffold."""

from __future__ import annotations

import os
import threading
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi import HTTPException
from fastapi.responses import FileResponse
from fastapi.responses import HTMLResponse

from trafficcam.api.routes import router, warm_dashboard_cache
from trafficcam.web.map_page import render_map_page


def _autostart_enabled() -> bool:
    return os.getenv("PIPELINE_AUTOSTART", "0").strip().lower() in {"1", "true", "yes", "on"}


def _autostart_limit() -> int | None:
    raw_value = os.getenv("PIPELINE_LIMIT", "").strip()
    if not raw_value:
        return None
    try:
        limit = int(raw_value)
    except ValueError:
        return None
    return limit if limit > 0 else None


def _live_loop_kwargs() -> dict[str, object]:
    return {
        "manifest_file": os.getenv("PIPELINE_MANIFEST_FILE", "data/manifest.json"),
        "output_dir": os.getenv("PIPELINE_OUTPUT_DIR", "output/live"),
        "data_dir": os.getenv("PIPELINE_DATA_DIR", "data"),
        "frame_count": 1,
        "limit": _autostart_limit(),
    }


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Start the live capture loop alongside the dashboard when enabled."""
    warm_dashboard_cache()
    if _autostart_enabled():
        def _live_loop() -> None:
            from trafficcam.config import settings
            from trafficcam.pipeline import run_pipeline

            run_pipeline(
                **_live_loop_kwargs(),
                interval=settings.capture_interval_seconds,
                max_cycles=None,
            )

        thread = threading.Thread(target=_live_loop, name="trafficcam-live-loop", daemon=True)
        thread.start()
    yield


app = FastAPI(title="Traffic Cam API", lifespan=lifespan)
app.include_router(router, prefix="/api")


def _resolve_output_asset(asset_path: str) -> Path:
    output_root = (Path.cwd() / "output").resolve()
    candidate = (output_root / asset_path).resolve()
    try:
        candidate.relative_to(output_root)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail="Unknown output asset") from exc
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail="Unknown output asset")
    return candidate


@app.get("/", response_class=HTMLResponse)
def dashboard() -> HTMLResponse:
    """Render the interactive congestion map."""
    return HTMLResponse(render_map_page())


@app.get("/output/{asset_path:path}")
def output_asset(asset_path: str) -> FileResponse:
    """Serve captured frames and debug overlays generated by the pipeline."""
    response = FileResponse(_resolve_output_asset(asset_path))
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    return response


@app.get("/health")
def health() -> dict:
    """Return a simple health response."""
    return {"status": "ok"}
